alias ls='ls -f --group-directories-first'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -lF'
alias lla='ll -a'
alias la='ls -A'
alias h='history'
